/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author tarcisio
 */
public class CalculoAnova extends javax.swing.JFrame {
    URL url = this.getClass().getResource("/img/X32.png");
    Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);

    public void setTitulo(Image iconeTitulo) {
        this.setIconImage(iconeTitulo);
    }

    /**
     * Creates new form Prototipo
     */
    public CalculoAnova() {
        initComponents();
        setTitle("Cálculo Anova One-Way");
        setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btAddTrat = new javax.swing.JButton();
        btRemovTrat = new javax.swing.JButton();
        btAddLinha = new javax.swing.JButton();
        btCalculaAnova = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAmostras = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tratamentos"));

        btAddTrat.setText("Adicionar Tratamento");
        btAddTrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddTratActionPerformed(evt);
            }
        });

        btRemovTrat.setText("Remover Tratamento");
        btRemovTrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemovTratActionPerformed(evt);
            }
        });

        btAddLinha.setText("Adicionar linha na coluna");
        btAddLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddLinhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btAddTrat)
                .addGap(18, 18, 18)
                .addComponent(btRemovTrat)
                .addGap(18, 18, 18)
                .addComponent(btAddLinha)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddTrat)
                    .addComponent(btRemovTrat)
                    .addComponent(btAddLinha))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btCalculaAnova.setText("Calcular Anova");
        btCalculaAnova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalculaAnovaActionPerformed(evt);
            }
        });

        tbAmostras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tratamento 1", "Tratamento 2", "Tratamento 3"
            }
        ));
        jScrollPane2.setViewportView(tbAmostras);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(btCalculaAnova)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCalculaAnova)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddTratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddTratActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tbAmostras.getModel();
        modelo.addColumn("Tratamento " + (modelo.getColumnCount() + 1));
        tbAmostras.setModel(modelo);
    }//GEN-LAST:event_btAddTratActionPerformed

    private void btAddLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddLinhaActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tbAmostras.getModel();
        Double[] novaLinha = null;
        modelo.addRow(novaLinha);
        tbAmostras.setModel(modelo);
    }//GEN-LAST:event_btAddLinhaActionPerformed

    private void btRemovTratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemovTratActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tbAmostras.getModel();
        if (modelo.getColumnCount() > 3) {
            modelo.setColumnCount(modelo.getColumnCount() - 1);
            tbAmostras.setModel(modelo);
        } else {
            JOptionPane.showMessageDialog(this, "Você precisa de tratamentos amostras ou mais para calcular a Anova!", "Erro!", HEIGHT);
        }
    }//GEN-LAST:event_btRemovTratActionPerformed

    private void btCalculaAnovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalculaAnovaActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tbAmostras.getModel();
        boolean[] temConteudo = new boolean[modelo.getColumnCount()];
        boolean podeCalcular = true;
        boolean erroConversao = false;
        String[][] dados = new String[modelo.getRowCount()][modelo.getColumnCount()];
        String dadosConcat = new String();

        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Você deve inserir valores na tabela antes de calcular a Anova!", "Erro!", JOptionPane.ERROR_MESSAGE);
        } else {

            for (int i = 0; i < modelo.getRowCount(); i++) {
                for (int j = 0; j < modelo.getColumnCount(); j++) {
                    dados[i][j] = (String) modelo.getValueAt(i, j);
                }
            }

            for (int i = 0; i < modelo.getColumnCount(); i++) {
                temConteudo[i] = false;
            }

            for (int i = 0; i < modelo.getColumnCount(); i++) {
                for (int j = 0; j < modelo.getRowCount(); j++) {
                    if (dados[j][i] == null || dados[j][i].isEmpty()) {
                        temConteudo[i] = false;
                    } else {
                        temConteudo[i] = true;
                        break;
                    }
                }
            }

            for (int i = 0; i < modelo.getColumnCount(); i++) {
                if (!temConteudo[i]) {
                    podeCalcular = false;
                    break;
                }
            }

            if (podeCalcular) {
                for (int i = 0; i < modelo.getColumnCount(); i++) {
                    for (int j = 0; j < modelo.getRowCount(); j++) {
                        try {
                            if (dados[j][i] != null && !dados[j][i].isEmpty()) {
                                dados[j][i] = dados[j][i].replace(",", ".");
                                Double.parseDouble(dados[j][i]);
                                dadosConcat = dadosConcat + dados[j][i] + ",";
                            }
                        } catch (NumberFormatException nfe) {
                            JOptionPane.showMessageDialog(this, "Digite apenas números reais!", "Erro!", JOptionPane.ERROR_MESSAGE);
                            break;
                        }
                    }
                    dadosConcat = dadosConcat + " ";
                }
                
                System.out.println(dadosConcat.replace(", "," "));
            } else {
                JOptionPane.showMessageDialog(this, "Todos os tratamentos devem conter dados!", "Erro!", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btCalculaAnovaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculoAnova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculoAnova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculoAnova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculoAnova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculoAnova().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddLinha;
    private javax.swing.JButton btAddTrat;
    private javax.swing.JButton btCalculaAnova;
    private javax.swing.JButton btRemovTrat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbAmostras;
    // End of variables declaration//GEN-END:variables
}
