/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author jehym
 */
public class XtatistiKPrincipal extends javax.swing.JFrame {
    URL url = this.getClass().getResource("/img/X32.png");
    Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
    
    public void setTitulo(Image iconeTitulo) {
        this.setIconImage(iconeTitulo);
    }
    /**
     * Creates new form Xtatistik_Principal
     */
    public XtatistiKPrincipal() {
        initComponents();
        setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbEscolha = new javax.swing.JComboBox();
        btAbrir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("XtatistiK");
        setResizable(false);

        jLabel1.setText("Selecione a operação desejada:");

        cbEscolha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha...", "Moda", "Detector de Outliers", "Tabela de Distribuição de Frequências com Intervalo de Classe", "Intervalo de Confiança", "Teste T - Tipo 1 (duas médias)", "Teste T - Tipo 2 (duas médias)", "Anova One-Way (duas ou mais médias)" }));
        cbEscolha.setToolTipText("");
        cbEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEscolhaActionPerformed(evt);
            }
        });

        btAbrir.setText("Abrir Tela de Cálculo");
        btAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(cbEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(btAbrir)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirActionPerformed
        
        switch(cbEscolha.getSelectedIndex()){
            case 0:
                JOptionPane.showMessageDialog(this, "Selecione uma opção válida!", "XtatistiK - Erro!", JOptionPane.ERROR_MESSAGE);
                break;
            case 1:
                System.out.println(cbEscolha.getSelectedIndex());
                CalculoModa cm = new CalculoModa();
                cm.setLocationRelativeTo(null);
                cm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                cm.setVisible(true);
                break;
            case 2:
                System.out.println(cbEscolha.getSelectedIndex());
                GUIBoxPlot detOut = new GUIBoxPlot();
                detOut.setLocationRelativeTo(null);
                detOut.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                detOut.setVisible(true); 
                break;
            case 3:
                System.out.println(cbEscolha.getSelectedIndex());
                CalculoDistFreq cdf = new CalculoDistFreq();
                cdf.setLocationRelativeTo(null);
                cdf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                cdf.setVisible(true);                
                break;
            case 4:
                System.out.println(cbEscolha.getSelectedIndex());
                GUIintervConf interConv = new GUIintervConf();
                interConv.setLocationRelativeTo(null);
                interConv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                interConv.setVisible(true);                
                break;
            case 5:
                System.out.println(cbEscolha.getSelectedIndex());
                GUITesteT tT1 = new GUITesteT();
                tT1.setLocationRelativeTo(this);
                tT1.setTitle("Verificação de Hipótese | T1");
                tT1.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                tT1.setVisible(true);                
                break;
            case 6:
                System.out.println(cbEscolha.getSelectedIndex());
                GUITesteT tT2 = new GUITesteT();
                tT2.setLocationRelativeTo(this);
                tT2.setTitle("Verificação de Hipótese | T2");
                tT2.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                tT2.setVisible(true);                
                break;
            case 7:
                System.out.println(cbEscolha.getSelectedIndex());
                CalculoAnova cao = new CalculoAnova();
                cao.setLocationRelativeTo(null);
                cao.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                cao.setVisible(true);                
                break;
        }
    }//GEN-LAST:event_btAbrirActionPerformed

    private void cbEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEscolhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEscolhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XtatistiKPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XtatistiKPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XtatistiKPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XtatistiKPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XtatistiKPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrir;
    private javax.swing.JComboBox cbEscolha;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
